export default [
  {
    files: ["www/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2015,
      sourceType: "script",
      globals: {
        // Browser
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        location: "readonly",
        history: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        XMLHttpRequest: "readonly",
        FormData: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        URL: "readonly",
        atob: "readonly",
        btoa: "readonly",
        Image: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        fetch: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        performance: "readonly",
        Worker: "readonly",
        HTMLElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLVideoElement: "readonly",
        screen: "readonly",
        getComputedStyle: "readonly",
        matchMedia: "readonly",
        MutationObserver: "readonly",

        // Development
        console: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",

        // Cordova / App globals
        cordova: "readonly",
        StatusBar: "readonly",
        angular: "readonly",
        ionic: "readonly",
        moment: "readonly",
        Masonry: "readonly",
        Packery: "readonly",
        Draggabilly: "readonly",
        imagesLoaded: "readonly",
        Chart: "readonly",
        saveAs: "readonly",
        chrome: "readonly",
        URI: "readonly",
        localforage: "readonly",
        CryptoJS: "readonly",
        Connection: "readonly",
        LZString: "readonly",
        vis: "readonly",
        timeline: "readonly",
        PushNotification: "readonly",
        ConnectSDK: "readonly",
        ContactFindOptions: "readonly",
        $: "readonly",
        MobileAccessibility: "readonly",
        hello: "readonly",
        DJS: "readonly",
        FirebasePlugin: "readonly",
        gifshot: "readonly",
        ReadableStream: "readonly",
        LibraryHelper: "readonly",
        GifWriter: "readonly",
        NeuQuant: "readonly",
        LocalFileSystem: "readonly",
        FileError: "readonly",
      },
    },
    rules: {
      // Enforcing (from jshint config)
      "no-bitwise": "error",
      "no-extend-native": "error",
      "no-caller": "error",

      // Off to match jshint's practical behavior on this codebase
      "no-undef": "off",
      "eqeqeq": "off",
      "curly": "off",
      "no-unused-vars": "off",
      "strict": "off",
      "no-loop-func": "off",
      "no-return-assign": "off",
      "dot-notation": "off",
    },
  },
];
